name: Build Vue
on:
  pull_request:
    types:
      - closed
    branches:
      - 'master'
jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: Build Vue
    steps:
    - uses: actions/checkout@v2
    - id: Build-Vue
      uses: xRealNeon/VuePagesAction@1.0.1
      with:
        username: 'devzom'
        reponame: 'vue-simpleselect'
        useyarn: true
        token: ${{ secrets.GITHUB_TOKEN }} # Leave this line unchanged
